spring:
  # 开发环境数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/personal_blog_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
# 日志配置
logging:
  level:
    root: info
    com.air846.blog: debug
    org.springframework.security: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace