spring:
  # 生产环境数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/personal_blog_prod?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      
# 日志配置
logging:
  level:
    root: warn
    com.air846.blog: info
  file:
    name: /var/log/blog/blog.log
    
# JWT配置
jwt:
  secret: ${JWT_SECRET:myProductionSecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}